language: node_js
cache: npm
install:
- pip install --user awscli
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make deploy; fi
branches:
  only:
  - master
env:
  global:
  - secure: oc5AnM9Ff/Ipb91iP0AnjQtz2JQpttzNQaAXYrWvR09SxRi6b4Ui3YC4oOk4+A7dgLExe9gmpVe6D3z4pz3EARnMiBnMQRL7d6KQnNkJrnZ8LqBMoMwSg1dzaBpTQ+Y62PkbtQzfi3Je9zFzDPc5pnXBIAH3XJBSl2Vt72hmotryuOoZlokswi1KmPxYzzO/j+OEzVa07FnRmSzL/rx0gYgwQNwu5iLEFdfhOYl8p72RH9R8J+I7C6Fc0QOoKFJ9uPLA+1qFIy/1Uejtxm37cU5BE3MfqxMXGSoQvcYby+Q+GPF/cXdzFsgwVgltE+xxD9GWx+OmDUNARnaQlMjkUr538Oq8EujfqDjv82bRUhfT3cykZSDD3oWPm7zfrSJVpN8Y5KfrV776dtv5xpwo+QHhGq/k+UZTAt8IDvQ7fMDV4OaELWvuDk6iiKX5rcxSRJOOEjVRDBPqUJ//i12Yqm/TPGfFSMwfQewKpxISu+kZ10h0rXeRvkTAwG9z+ybIm7+Ce0jJhSgeAVtL1CJ7neIxKqWj3sFB7Wl94iGpb9GSokywHdZv2I14Hjh//3zwz05+pqJu8LyHM/kAfvRrdwOXWGUUmTFndlX5KeAfbRi66wCuE8zAHFVqHV/i83vj97Vvgypm1TATPIHGOP21DF5Sl9z6NebRGYuqweFnPDg=
  - secure: MC5zyyaAJ+eoduO+P+u3IP7cAFu9YXFIoSYJrZpmoikZCIi2onaQOPahZuNFBWEaEcp00SS2VB4uITdYON//XHqMKgyw06MqYm2ULNJW4R1RYezJM0Qujx7Sc2aQjbXNJhl8sZ9138zP7ke7/KJAgkeNRaiAHfnwRkOl2MdB0vniclf90ZraqH7Qr2ryy1quL0Jpxj2arUE6H5qkKLiwiUpnL6UefjSkF3BgxH0NxqBHdxnY9M8GEGPkO08/lIieAcZ7RGJW2gd7OKw+QRl1GEhyuE4E3m1tDmSc4PI0shd1/n8eeRdgHAA69jNAEzwWYelgYh8OKd7kaZBEX8NFcbZuujNmHSuBSgaJ0sDd02YhrwsjiMOGyhyXqcQm5MH6jA6/pLmEgtEUt0VlWS0XK/8KTTqyl1cFWjqkrD+Z3PM3bTSRHU6QUyR3qL5Q5T5BV2L61AGBMGXXtmsl1d2gW7obcVINFTMz95zczO8nkRmLz08Ihsi0qJPxMsRFGrR8iunjFGYeodRByk5bJfNV2WoAAFQm+3sJNg/aaVsb/GvQDi9x1ciuwc01kdEJUSVlOPkaiGHkMqmQ7HyecjES5pSx7H0ppwTSNnNXMfN+SkwxtmrypQhcymS7B8E7sK5C5jC+7Fj4qEUhd6KtkJuT4sPRBokEkN2AsFBpiRgbtZM=
